### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by ZacharyKhan** [rutgerfarry/FreshFades#7]
I see the website for Corvallis Fresh Fades is no longer active. 

Is this business still around? If so, I’d love to help on the app. I’m an OSU student and feel like we really need an OG place to get a good haircut.

**Comment by rutgerfarry** [comment]
Hey Zach thanks for reaching out! I know the owner shut down his original location and was hoping to eventually start the business up again in Southtown. This app project kinda fell into limbo since then, and now that I've left Corvallis I'm no longer interested in working on it 😕

If you want to check out the project though I'll leave it up! 

closed by: f7be2a77e34a811f2b66ab4d9b65517ede26a729
